/// interception const values
interception["KEY_DOWN"] = INTERCEPTION_KEY_DOWN;
interception["KEY_UP"] = INTERCEPTION_KEY_UP;
interception["KEY_E0"] = INTERCEPTION_KEY_E0;
interception["KEY_E1"] = INTERCEPTION_KEY_E1;
interception["KEY_TERMSRV_SET_LED"] = INTERCEPTION_KEY_TERMSRV_SET_LED;
interception["KEY_TERMSRV_SHADOW"] = INTERCEPTION_KEY_TERMSRV_SHADOW;
interception["KEY_TERMSRV_VKPACKET"] = INTERCEPTION_KEY_TERMSRV_VKPACKET;
interception["FILTER_KEY_NONE"] = INTERCEPTION_FILTER_KEY_NONE;
interception["FILTER_KEY_ALL"] = INTERCEPTION_FILTER_KEY_ALL;
interception["FILTER_KEY_DOWN"] = INTERCEPTION_FILTER_KEY_DOWN;
interception["FILTER_KEY_UP"] = INTERCEPTION_FILTER_KEY_UP;
interception["FILTER_KEY_E0"] = INTERCEPTION_FILTER_KEY_E0;
interception["FILTER_KEY_E1"] = INTERCEPTION_FILTER_KEY_E1;
interception["FILTER_KEY_TERMSRV_SET_LED"] = INTERCEPTION_FILTER_KEY_TERMSRV_SET_LED;
interception["FILTER_KEY_TERMSRV_SHADOW"] = INTERCEPTION_FILTER_KEY_TERMSRV_SHADOW;
interception["FILTER_KEY_TERMSRV_VKPACKET"] = INTERCEPTION_FILTER_KEY_TERMSRV_VKPACKET;
interception["MOUSE_LEFT_BUTTON_DOWN"] = INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN;
interception["MOUSE_LEFT_BUTTON_UP"] = INTERCEPTION_MOUSE_LEFT_BUTTON_UP;
interception["MOUSE_RIGHT_BUTTON_DOWN"] = INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN;
interception["MOUSE_RIGHT_BUTTON_UP"] = INTERCEPTION_MOUSE_RIGHT_BUTTON_UP;
interception["MOUSE_MIDDLE_BUTTON_DOWN"] = INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN;
interception["MOUSE_MIDDLE_BUTTON_UP"] = INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP;
interception["MOUSE_BUTTON_1_DOWN"] = INTERCEPTION_MOUSE_BUTTON_1_DOWN;
interception["MOUSE_BUTTON_1_UP"] = INTERCEPTION_MOUSE_BUTTON_1_UP;
interception["MOUSE_BUTTON_2_DOWN"] = INTERCEPTION_MOUSE_BUTTON_2_DOWN;
interception["MOUSE_BUTTON_2_UP"] = INTERCEPTION_MOUSE_BUTTON_2_UP;
interception["MOUSE_BUTTON_3_DOWN"] = INTERCEPTION_MOUSE_BUTTON_3_DOWN;
interception["MOUSE_BUTTON_3_UP"] = INTERCEPTION_MOUSE_BUTTON_3_UP;
interception["MOUSE_BUTTON_4_DOWN"] = INTERCEPTION_MOUSE_BUTTON_4_DOWN;
interception["MOUSE_BUTTON_4_UP"] = INTERCEPTION_MOUSE_BUTTON_4_UP;
interception["MOUSE_BUTTON_5_DOWN"] = INTERCEPTION_MOUSE_BUTTON_5_DOWN;
interception["MOUSE_BUTTON_5_UP"] = INTERCEPTION_MOUSE_BUTTON_5_UP;
interception["MOUSE_WHEEL"] = INTERCEPTION_MOUSE_WHEEL;
interception["MOUSE_HWHEEL"] = INTERCEPTION_MOUSE_HWHEEL;
interception["FILTER_MOUSE_NONE"] = INTERCEPTION_FILTER_MOUSE_NONE;
interception["FILTER_MOUSE_ALL"] = INTERCEPTION_FILTER_MOUSE_ALL;
interception["FILTER_MOUSE_LEFT_BUTTON_DOWN"] = INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN;
interception["FILTER_MOUSE_LEFT_BUTTON_UP"] = INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP;
interception["FILTER_MOUSE_RIGHT_BUTTON_DOWN"] = INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN;
interception["FILTER_MOUSE_RIGHT_BUTTON_UP"] = INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP;
interception["FILTER_MOUSE_MIDDLE_BUTTON_DOWN"] = INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN;
interception["FILTER_MOUSE_MIDDLE_BUTTON_UP"] = INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP;
interception["FILTER_MOUSE_BUTTON_1_DOWN"] = INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN;
interception["FILTER_MOUSE_BUTTON_1_UP"] = INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP;
interception["FILTER_MOUSE_BUTTON_2_DOWN"] = INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN;
interception["FILTER_MOUSE_BUTTON_2_UP"] = INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP;
interception["FILTER_MOUSE_BUTTON_3_DOWN"] = INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN;
interception["FILTER_MOUSE_BUTTON_3_UP"] = INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP;
interception["FILTER_MOUSE_BUTTON_4_DOWN"] = INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN;
interception["FILTER_MOUSE_BUTTON_4_UP"] = INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP;
interception["FILTER_MOUSE_BUTTON_5_DOWN"] = INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN;
interception["FILTER_MOUSE_BUTTON_5_UP"] = INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP;
interception["FILTER_MOUSE_WHEEL"] = INTERCEPTION_FILTER_MOUSE_WHEEL;
interception["FILTER_MOUSE_HWHEEL"] = INTERCEPTION_FILTER_MOUSE_HWHEEL;
interception["FILTER_MOUSE_MOVE"] = INTERCEPTION_FILTER_MOUSE_MOVE;
interception["MOUSE_MOVE_RELATIVE"] = INTERCEPTION_MOUSE_MOVE_RELATIVE;
interception["MOUSE_MOVE_ABSOLUTE"] = INTERCEPTION_MOUSE_MOVE_ABSOLUTE;
interception["MOUSE_VIRTUAL_DESKTOP"] = INTERCEPTION_MOUSE_VIRTUAL_DESKTOP;
interception["MOUSE_ATTRIBUTES_CHANGED"] = INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED;
interception["MOUSE_MOVE_NOCOALESCE"] = INTERCEPTION_MOUSE_MOVE_NOCOALESCE;
interception["MOUSE_TERMSRV_SRC_SHADOW"] = INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW;

/// interception keyboard keycode
interception["KC_ESC"]           = 1;
interception["KC_1"]             = 2;
interception["KC_2"]             = 3;
interception["KC_3"]             = 4;
interception["KC_4"]             = 5;
interception["KC_5"]             = 6;
interception["KC_6"]             = 7;
interception["KC_7"]             = 8;
interception["KC_8"]             = 9;
interception["KC_9"]             = 10;
interception["KC_0"]             = 11;
interception["KC_HYPHEN"]        = 12; // -
interception["KC_CARET"]         = 13; // ^
interception["KC_BACK"]          = 14;
interception["KC_TAB"]           = 15;
interception["KC_Q"]             = 16;
interception["KC_W"]             = 17;
interception["KC_E"]             = 18;
interception["KC_R"]             = 19;
interception["KC_T"]             = 20;
interception["KC_Y"]             = 21;
interception["KC_U"]             = 22;
interception["KC_I"]             = 23;
interception["KC_O"]             = 24;
interception["KC_P"]             = 25;
interception["KC_ATMARK"]        = 26; // @
interception["KC_LEFT_BRACKET"]  = 27; // [
interception["KC_RETURN"]        = 28;
interception["KC_CONTROL"]       = 29;
interception["KC_A"]             = 30;
interception["KC_S"]             = 31;
interception["KC_D"]             = 32;
interception["KC_F"]             = 33;
interception["KC_G"]             = 34;
interception["KC_H"]             = 35;
interception["KC_J"]             = 36;
interception["KC_K"]             = 37;
interception["KC_L"]             = 38;
interception["KC_SEMI_COLON"]    = 39; // ;
interception["KC_COLON"]         = 40; // :
interception["KC_RIGHT_BRACKET"] = 43; // ]
interception["KC_AUTO"]          = 41; // 半角／全角
interception["KC_LSHIFT"]        = 42;
interception["KC_Z"]             = 44;
interception["KC_X"]             = 45;
interception["KC_C"]             = 46;
interception["KC_V"]             = 47;
interception["KC_B"]             = 48;
interception["KC_N"]             = 49;
interception["KC_M"]             = 50;
interception["KC_COMMA"]         = 51; // ,
interception["KC_PERIOD"]        = 52; // .
interception["KC_SLASH"]         = 53; // /
interception["KC_RSHIFT"]        = 54;

interception["KC_DIVIDE"]        = 53; // テンキー / {E0}
interception["KC_MULTIPLY"]      = 55; // テンキー *
interception["KC_MINUS"]         = 74; // テンキー -
interception["KC_PLUS"]          = 78; // テンキー +
interception["KC_NUMPAD_PERIOD"] = 83; // テンキー .
interception["KC_NUMPAD0"]       = 82; // テンキー 0
interception["KC_NUMPAD1"]       = 79; // テンキー 1
interception["KC_NUMPAD2"]       = 80; // テンキー 2
interception["KC_NUMPAD3"]       = 81; // テンキー 3
interception["KC_NUMPAD4"]       = 75; // テンキー 4
interception["KC_NUMPAD5"]       = 76; // テンキー 5
interception["KC_NUMPAD6"]       = 77; // テンキー 6
interception["KC_NUMPAD7"]       = 71; // テンキー 7
interception["KC_NUMPAD8"]       = 72; // テンキー 8
interception["KC_NUMPAD9"]       = 73; // テンキー 9

interception["KC_SNAPSHOT"]      = 55; // PrintScreen {E0}
interception["KC_ALT"]           = 56;
interception["KC_SPACE"]         = 57;
interception["KC_CAPITAL"]       = 58; // CAPS LOCK
interception["KC_PAUSE"]         = 69; // {E1}
interception["KC_SCROLL"]        = 70;
interception["KC_UP"]            = 72; // {E0}
interception["KC_LEFT"]          = 75; // {E0}
interception["KC_RIGHT"]         = 77; // {E0}
interception["KC_DOWN"]          = 80; // {E0}

interception["KC_F1"]            = 59;
interception["KC_F2"]            = 60;
interception["KC_F3"]            = 61;
interception["KC_F4"]            = 62;
interception["KC_F5"]            = 63;
interception["KC_F6"]            = 64;
interception["KC_F7"]            = 65;
interception["KC_F8"]            = 66;
interception["KC_F9"]            = 67;
interception["KC_F10"]           = 68;
interception["KC_F11"]           = 87;
interception["KC_F12"]           = 88;

interception["KC_NUMLOCK"]       = 69;
interception["KC_HOME"]          = 71;
interception["KC_PRIOR"]         = 73; // PageUp
interception["KC_END"]           = 79;
interception["KC_NEXT"]          = 81; // PageDown
interception["KC_INSERT"]        = 82;
interception["KC_DELETE"]        = 83;
interception["KC_APPS"]          = 91; // WINDOWS
interception["KC_KANA"]          = 112;
interception["KC_UNDERBAR"]      = 115; // \ _
interception["KC_FUNCTION"]      = 117;
interception["KC_PIPELINE"]      = 125; // \ |
interception["KC_CONVERT"]       = 121; // 変換
interception["KC_NONCONVERT"]    = 123; // 無変換
